-- OPTIONAL, and an example rather than something to paste unchanged: it pins
-- Teams to one workspace on one monitor. Skip it entirely if you would rather
-- Teams open wherever you are.
--
-- Append to the END of ~/.config/hypr/hyprland.lua. The end matters: if you
-- use hyprmoncfg, its dofile is the last line and regenerates monitor config
-- on every start, so anything placed above it can be overridden.
--
-- Replace "eDP-1" with your own monitor -- `hyprctl monitors -j` lists them.
-- The first rule anchors workspace 1 to that output; without it Hyprland puts
-- the workspace on whichever monitor opened it first, which varies between
-- boots. The second sends Teams to that workspace.
--
-- If you use this, also set the widget's `homeWorkspace` setting to the same
-- workspace, so unhiding returns Teams there instead of dragging it to
-- whichever workspace you happen to be on:
--
--   omarchy bar set io.github.haripako.teams homeWorkspace 1
--
-- Note hl.workspace_rule takes a table; positional arguments are rejected.
--
-- The window pattern is matched against the window CLASS, and it has to be the
-- class of whichever Teams you actually run -- this is the one place the widget
-- cannot cover for you, because Hyprland evaluates the rule when the window is
-- mapped. `^chrome-teams` is the web app; `teams-for-linux` is that native
-- client. Check yours with `hyprctl clients -j` and keep only what you use.
--
-- Match on the class and not the title: a browser window is mapped as
-- "Untitled" and only becomes "… | Microsoft Teams" afterwards, by which time
-- the rule has already been evaluated.
hl.workspace_rule({ workspace = "1", monitor = "eDP-1" })
o.window("^(chrome-teams|teams-for-linux)", { workspace = "1" })
